config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,:controllers => { :registrations => "registrations" }
  root "pages#home"
  get "people" => "registrations#index"
  get "settings" => "registrations#edit"

  resources :registrations, only: [:index, :show, :edit, :update, :destroy], :path=>'' do
    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg image/png)
  validates :name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :username, :exclusion => %w(about blog application books likes pages passwords profiles recommendations registrations users manuscripts stories jobs plans account admin signin signout signup help new popular shop tour)
    
  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

	 def configure_permitted_parameters
	   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :username, :email, :password) }
	   devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
	   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :password_confirmation, :photo, :miniresume, :linkedin, :twitter, :facebook, :username) }
	 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

def new
	super
end

def update
  super
end

def update_resource(resource, params)
 	resource.update_without_password(params)
end


def resource_name
	:user
end

def devise_mapping
	@devise_mapping ||= Devise.mappings[:user]
end

def after_update_path_for(resource)
  root_path
end

def index
	@users = User.all
end

def show
	@user = User.find_by_username(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>

	    <%= link_to "TheDiasporaProject", root_path, class: "navbar-brand" %>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav navbar-left">
	      <li><a href="#">Syndicates</a></li>
	      <li><a href="#">Companies</a></li>
	      <li><%= link_to "People", people_path %></li>
	    </ul>
	    </ul>
	   	<ul class="nav navbar-nav navbar-right">

	   
	   		<% if user_signed_in? %>
	   		<li><%= link_to "Settings", settings_path %></li>
	   		<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	   		<li class="round-image-28"><%= image_tag(current_user.photo.url(:thumb)) %></li>
	   	<% else %>
	   		<li><%= link_to "Join", new_user_registration_path %></li>
	     	<li><%= link_to "Log in", new_user_session_path %></li>

	      
	    <% end %>  

	    </ul>
	  </div><!-- /.navbar-collapse -->

	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheDiasporaProject - Where people of african and african caribbean heritage can invest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel='stylesheet' id='sd-fonts-css'  href='http://fonts.googleapis.com/css?family=Lato:400,300,700&subset=latin,latin-ext&ver=1.0.0' type='text/css' media='all' />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render 'layouts/header' %>
	<%= yield %>

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>

</body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>

<div class="container">
<h1>Activity Feed</h1>
<p>New Companies Created</p>
<p>New Syndicates Created</p>
<p>Syndicates Updates</p>
</div>

<% else %>

<div class="first-screen" style="background: url('/assets/main-guy.jpg') 50% 50% / cover; box-shadow: 1500px 313px rgba(0, 0 ,0, 0.31) inset;">
    <div class="row">
        <div class="col-md-6" style="color: #fff;">
            <br>
            <br>
            <h1 class="text-shadow">The<strong>Diaspora</strong>Project</h1>
            <h2 class="text-shadow">Where people of african <br>and african caribbean heritage can invest</h2>
            <!--<div class="text-shadow">
                <p>SD Business is a fully responsive, customizable, powerful and lightweight WordPress theme that will introduce your business in the most elegant way. </p> -->
				<div class="hompage_margin_bottom">
					<a href="index.html#advantages" class="button _filled-white-grey scroll-link highlighted">Raise Money Online</a>
					<a href="index.html#reviews" class="button _white scroll-link highlighted">Invest in a company</a>
				</div>
            </div>
        </div>
    </div>
</div>

<% end %>